### PR TITLE
Implement CloneExpression for PhiFunction

### PR DESCRIPTION
**Pull request by ptomin**
Implement `CloneExpression` for `PhiFunction`

### CODE REVIEW

**Comment by uxmal** [comment]
Have you run the regression tests as well? Were there any differences?

**Comment by ptomin** [comment]
No differences, off course. `Travis` should discover any difference in regression tests output

**Comment by ptomin** [comment]
The only difference is that one `PySample` error has gone away (but output files are the same)

**Comment by uxmal** [comment]
I'm just surprised that there weren't more changes, considering that the exception this PR fixes was occurring a lot in the regression tests. Never mind then; pulling....

**Comment by ptomin** [comment]
It should affect `regression.log` but I could not push my version of this file because I  have different locale

**Pull request merged**
