### PR TITLE
Possible fix for #266

### PR DESCRIPTION
**Pull request by ptomin**

### CODE REVIEW

**Comment by Lukas-Dresel** [comment]
I don't think this fix is correct. What about the other instances of casting to Address? Wouldn't that still crash because Address and EmptyEditorModel are incompatible?

**Comment by ptomin** [comment]
@Lukas-Dresel Workflow described in #266 does not cause exception after this fix. Are there other workflows  that cause cast exceptions?

@uxmal What do you think about it?

**Comment by Lukas-Dresel** [comment]
Ah, i misunderstood the as-operator. What about the other listed instances?

**Comment by uxmal** [comment]
Although this may fix the immediate issue  (crash) it doesn't fix the cause of the issue,  which is that when the user clicks on the alphanumeric dump, the memory control erroneously fires a selection event with a null address.  The "real " fix is to either not raise the event,  or better yet, fire the event with a valid address since the alphanumeric characters can all be mapped to addresses.

@ptomin : please check the other places where the position is being cast to address. Once you're satisfied update this PR. This will fix the symptom. However leave #266 open and I will fix the root issue.

@

**Comment by ptomin** [comment]
@uxmal @Lukas-Dresel I have replaced casts with `as` operators. Now it's time to merge it

**Pull request merged**
