### PR TITLE
Add unit tests for MixedCodeDataModel::GetLineSpans

### PR DESCRIPTION
**Pull request by ptomin**
I have added two unit tests to reproduce problems with MixedCodeDataModel::GetLineSpans method.

John, is it correct that MemoryArea size is larger than ImageSegment? It causes exception when viewing code in pySample.dll from 0x10001900 address (see Mcdm_GetLineSpans_MemoryAreaIsLargerThanSegment to reproduce)

### CODE REVIEW

**Comment by uxmal** [comment]
A `MemoryArea` can be associated with one or more `ImageSegments`. In the case of a MS-DOS executable, where the memory used by the binary is always "compact", the MS-DOS image loader yields:
```
+----------------+  +---------------+  +---------------+
| ImageSegment 1 |  | ImageSegment2 |  | ImageSegment3 |
+----------------+  +---------------+  +---------------+
        v                   v                  v
+------------------------------------------------------+
| MemoryArea                                           |
+------------------------------------------------------+
```
ELF and PE image may be very sparse, with "gaps" of several hundred megabytes of address space. A monolithic chunk of MemoryArea would still be possible but it would be a tremendous waste of address space:
```
+----------------+  +---------------+  +---------------+
| ImageSegment 1 |  | ImageSegment2 |  | ImageSegment3 |
+----------------+  +---------------+  +---------------+
        v                   v                  v
+----------------+  +---------------+  +---------------+
| MemoryArea 1   |  | MemoryArea 2  |  | MemoryArea 3  |
+----------------+  +---------------+  +---------------+
```
Both of these scenarios must be handled in Reko code. In particular, MemoryAreas may exceed in address space the ImageSegments they are associated with.

I will take a look at this PR later today.

**Comment by ptomin** [comment]
> In particular, MemoryAreas may exceed in address space the ImageSegments

... so Mcdm_GetLineSpans_MemoryAreaIsLargerThanSegment test is correct and GetLineSpans should be modified to process this case

**Comment by uxmal** [comment]
Yes; I will be working on that later today -- unless you wish to take stab at it of course.

**Comment by uxmal** [comment]
Thanks for the unit tests. The f43083d commit fixes a bunch of crashes, but now scrolling to the bottom is blowing up. I will look at that tomorrow.

**Pull request merged**
