### PR TITLE
 Mofify regressionTests.py to strip SSA identifier names

### PR DESCRIPTION
**Pull request by ptomin**
Mofify `regressionTests.py` to strip SSA identifier names.
```
eax_7 -> eax_n
Eq_56 -> Eq_n
```

### CODE REVIEW

**Comment by uxmal** [comment]
@ptomin : could you add a new switch `--strip-suffixes`? I still find it useful to look at the "ground truth" when bug hunting.

**Comment by ptomin** [comment]
I have create `--no-strip-suffixes` option to strip suffixes by default

**Comment by uxmal** [comment]
I'm a little hesitant about introducing a "negative" switch: `--no-strip-suffixes`. I'd rather see `--strip-suffixes`. Is this OK with you?

**Comment by ptomin** [comment]
I want to strip suffixes by default so that just simple run of `regressionTests.py` does appropriate job. So there are two possibilities:
- Introducing `--no-strip-suffixes`
- Introducing `-strip-suffixes=yes/no` (default value is `yes`)

**Comment by uxmal** [comment]
Let's go with the latter option: I'm fine with defaulting to `--strip-suffixes:yes`

**Comment by ptomin** [comment]
Done in 49e149e. Could be merged?

**Comment by uxmal** [comment]
Looks good, thanks.

**Pull request merged**
