### PR TITLE
x86-16 fix rewrite of push cs; call near func; by converting it to a real far call

### PR DESCRIPTION
**Pull request by blindmatrix**
I didn't add any new tests but updated old once. There where 2 unit tests and a regression that failed. The regression I've read and I can't see anything that looks incorrect, but a second pair of eyes on the regression outputs would be appreciated.

This will only fix calls that abuse near relative calls prefixed with `push cs`. I have yet to see this being used with a `push cs` followed by an indirect near call. It might exist, but it's nothing I've seen so far.

I ran the regressions with Python3.

Also, there was a failure in `subjects/PE/x86/RussianText/RussianText.reko/RussianText.globals.c` but that also happens before this change, so I'm ignoring that :P

So, tests will fail until AppVeyor run Python3 or regressionTests.py gets fixed for Python2, and RussionText is solved.

### CODE REVIEW

**Comment by blindmatrix** [comment]
Maybe I should add a specific test after all too... I'll look into it at lunch tomorrow

**Comment by uxmal** [comment]
I'm not convinced that always treating a pushed `cs` register as part of the return address is a safe assumption, although clearly it is used frequently to make near calls to far procedures in the same segment as the caller. I'm concerned this might introduce problems for code which passes a segment selector as a parameter on the stack.

Reko should be recording, for each `Procedure`, how it affects the stack as it returns to its caller. In the `RtlReturn` class there is a `ReturnAddressBytes` property, which should be getting propagated to the `StackDelta` property of the `Procedure.Signature` instance during the scanning phase. There are known problems with this, but it should be working for most procedures. I will look at #881 and see if I can make some changes that improve the generated output.

**Comment by blindmatrix** [comment]
I have opinions :P

I have some suggested paths forward.

The best approach (I think) would be to mark procedures as near/far/undefined when scanning (or based on CSignature). If the procedure is marked as far, but called using `push cs; call near;`, then this should be applied. There should of course be an option to override this, globally and/or per call site.

The second approach (which probably is a bit lazy) would be to assume this is always correct, but again with an option to override globally and or locally.

I can see the point of tracking StackDelta too, but if you know the target is _far_ but called with this setup, then I think it's clearer to let the Rewriter produce the intended semantics.

However, if you had instructions between the _push_ and the _call_ then my approaches would fail. This could be handled later as a pass, but I have yet to see that in a real binary, as this is a specific pattern produced by some compilers.

But I'm curious about a sample where `push cs; call near;` is actually used but not targeting a _far_ procedure.

Also as a side note, I don't think the current patch would break more then the existing code. As far as I can see only SP gets updated, CS never get stored in the current output, meaning no existing decompilation should (hopefully) break more then I think it might already be :P

**Comment by uxmal** [comment]
I went ahead and pulled the PR. It's unlikely to see the sequence `push cs / call <near>` and it isn't a call to a `far` procedure. Thanks for the PR and patience!

**Pull request merged**
