### PR TITLE
Fixed bug in x86 disassembler

### PR DESCRIPTION
**Pull request by Lukas-Dresel**
New and improved. Unit-tests coming soon.

### CODE REVIEW

**Comment by ptomin** [comment]
@Lukas-Dresel  There are 7 failed unit tests after this PR

**Comment by Lukas-Dresel** [comment]
I'll take a look at it soon, sorry, didn't see this until now

**Comment by Lukas-Dresel** [comment]
@ptomin: With pull request #273 all the unit-tests pass, was a simple copy-paste error on my part

**Comment by ptomin** [comment]
Now, all unit tests pass, thanks.

**Pull request merged**
