### PR TITLE
Add '_CIexp' and '_control87' to 'msvcrt.inc'

### PR DESCRIPTION
**Pull request by ptomin**

### CODE REVIEW

**Comment by uxmal** [comment]
Ready to merge?

**Comment by ptomin** [comment]
`SlibReadMsvcrtXml` unit test failed

**Comment by ptomin** [comment]
This test looks useless

**Comment by uxmal** [comment]
I agree, it doesn't seem to do any useful work. Remove it.

**Comment by ptomin** [comment]
Fixed in 284152e

**Pull request merged**
