### PR TITLE
Fix analysis unit tests - linux

### PR DESCRIPTION
**Pull request by nemerle**
Mostly /r/n issues + one filename case difference.

Seems one of the committed files had different line endings though :cry:

### CODE REVIEW

**Comment by uxmal** [comment]
Thanks for this. Could you please adhere to the coding style of the code base, which is: all methods, properties, and events of classes and structs are **C**apitalized, regardless of whether they are public or private.

**Comment by uxmal** [comment]
Also, consider use the `params` keyword to avoid having to create string arrays manually; ie. instead of
```c#
public void foo(string [] args) // ...

foo(new[] { "hello", "world" });
```
instead write
```c#
public void foo(params string [] args) // ...

foo("hello", "world");
```
You'll see examples of this sprinkled liberally in the reko codebase.

**Comment by nemerle** [comment]
will do

**Comment by nemerle** [comment]
done.. 

Also please note that SsaTransformTests and TrashedRegsiterFinder2Tests fail on linux. - this is related to #27, just converting their sources to unix line endings fixes them.

**Pull request merged**
