### PR TITLE
VCExeSample: create function with indirect call

### PR DESCRIPTION
**Pull request by ptomin**
VCExeSample: create function with indirect call

### CODE REVIEW

**Comment by ptomin** [comment]
Also see https://github.com/uxmal/reko/commit/d4dc1aaa2a889e3a550ea64d6bc11fa178e52a73#commitcomment-18013103

**Comment by uxmal** [comment]
Have you tried distilling the error into a unit test? Regardless  I will take a look this evening.

**Comment by ptomin** [comment]
Maybe 04f4604 could be useful

**Comment by ptomin** [comment]
.. see #258

**Comment by ptomin** [comment]
Maybe b8ce737 could be possible fix for it

**Comment by ptomin** [comment]
@uxmal what do you think about  b8ce737? It's not final version and should be improved, off course

**Pull request merged**
