### PR TITLE
Fix Travis build

### PR DESCRIPTION
**Pull request by ptomin**

### CODE REVIEW

**Comment by ptomin** [comment]
Finally `Travis` build passed. Could be merged now

**Comment by smx-smx** [comment]
Good, that also fixed the Appveyor build, which now fails to run the tests. It tries to use .NET 3.5 but it should be using the same version that reko is built with, i.e .NET 4.5

**Comment by uxmal** [comment]
@ptomin :  ты герой!  I will review the PR in a few hours when I'm back at the keyboard

**Comment by uxmal** [comment]
I will work on getting the appveyor unit tests working. Again, thanks all for your help in getting the tests back on the rails again.

**Pull request merged**
