### PR TITLE
Small fixes

### PR DESCRIPTION
**Pull request by mjunix**
I don't have any experience with this code base so someone should probably review this before merging.

### CODE REVIEW

**Comment by uxmal** [comment]
Hej, och tack för din pull request! You've found quite a few cut'n'paste bugs that have been there for a long time, much appreciated!

However, the PR as it is right now cannot be merged because a few hundred unit tests are failing. You can run the unit test suite by either

1. Running from the command line by changing directory to `$REKO_DIR/src/UnitTests` and running:
```
dotnet test -p:Platform=x64
```
2. Or by running them in an IDE like VStudio.

At first glance, it looks like the file  `$REKO_DIR/src/x86/Assembler/X86Assembler.cs` needs to changed to allow for the possibility of assembler language statements like:
```
mov eax,+8
```
where the immediate operand on the right is allowed to be smaller than the register operand on the left. Do you feel confident enough to make the required fixes to make the unit tests pass?

Also, as a first-time contributor, please don't forget to add yourself to the `$REKO_DIR/AUTHORS` file!

**Comment by mjunix** [comment]
> Do you feel confident enough to make the required fixes to make the unit tests pass?

Sorry, but I do not.

**Comment by uxmal** [comment]
> 
> Sorry, but I do not.

Np, I'll clean up. Don't forget to add your name to `AUTHORS` though.

**Comment by uxmal** [comment]
I fixed the broken unit tests. Thanks for your contribution!

**Pull request merged**
