### PR TITLE
Add missing msdos API

### PR DESCRIPTION
**Pull request by xor2003**

### CODE REVIEW

**Comment by ptomin** [comment]
One unit test failed:
Reko.UnitTests.Core.Serialization.SerializedLibraryTests.SlibReadRealModeIntServices:
  Expected: 89
  But was:  95

**Comment by uxmal** [comment]
Thanks for the contribution!  As a new contributor, how do you wish to be credited in AUTHORS?

**Comment by uxmal** [comment]
The unit test should easily be fixed. Which one of you can assist here? I can alas not compile anything until Tuesday.

**Comment by ptomin** [comment]
I have fixed it. See #284 pull request.

**Comment by xor2003** [comment]
Credit me as x0r.
1. Unfortunately I'm not familiar with C# (only C++) and this project.
2. Why don't you work together with radare2?

**Pull request merged**
