### PR TITLE
ArrayAccess and Slice matching is not implemented

### PR DESCRIPTION
**Pull request by ptomin**
Create unit tests for `ExpressionMatcher`

### CODE REVIEW

**Comment by ptomin** [comment]
Fixed in a2c60e3

**Comment by uxmal** [comment]
Pavel, do you want to implement the pattermatching for those two cases before I pull the request?

**Comment by ptomin** [comment]
At the moment, I'm not ready to do full implementation of it

**Comment by ptomin** [comment]
I think it could be merged as is

**Pull request merged**
