### PR TITLE
Add function returns pointer to integer as C parser test

### PR DESCRIPTION
**Pull request by ptomin**

### CODE REVIEW

**Comment by ptomin** [comment]
I have modified `CParser` in two places and added two unit tests to reproduce it. Now this PR could be merged

**Comment by ptomin** [comment]
1. I see I have added integration with `AppVeyor`. Is it better than `Travis`?
2. `Travis` failed on regression tests. It shows differences in `CB80` files. There are no such changes on my machine

**Comment by smx-smx** [comment]
AppVeyor does Windows builds, Travis does Linux ones. There's currently some build problem with AppVeyor related to dependencies order which makes it fail build

**Comment by uxmal** [comment]
Disregard the AppVeyor error for now. We trying to figure out why it is failing in the `appveyor` branch. @ptomin: as for the Travis failure, I see you've created a separate branch for that too. I seem to have missed that the build has been failing for a while. I'm going to pull this PR because the CB80 error is not related to the changes you've made in this PR.

**Pull request merged**
