### PR TITLE
Create unit test to reproduce OutOfMemory exception thrown by VectorBuilder

### PR DESCRIPTION
**Pull request by ptomin**
Create unit test to reproduce `OutOfMemory` exception thrown by `VectorBuilder`

### CODE REVIEW

**Comment by ptomin** [comment]
Fix coming soon...

**Comment by ptomin** [comment]
The reason of `Travis` failure is `TLCS`

**Comment by uxmal** [comment]
Impressive work, Pavel. l'll look at the TLCS issue if you haven't started already.

**Comment by uxmal** [comment]
The break in TLCS is working in `scanner-development`. I will make `master` work again by adding relevant files.

**Comment by uxmal** [comment]
Build break was fixed in 949184442692902228288bf67e79b2dcfedae35c. Thanks so much for chasing this down, Pavel!

**Pull request merged**
