### PR TITLE
Add regression tests to the Travis CI script (Final version)

### PR DESCRIPTION
**Pull request by ptomin**
Now, it's ready to be merged into master

### CODE REVIEW

**Comment by uxmal** [comment]
Pavel, looks like the CI build failed. Could you look into it?

**Comment by ptomin** [comment]
Please merge #293 before and it will be passed

**Comment by ptomin** [comment]
It's OK now. So it could be merged

**Comment by uxmal** [comment]
Looking good

**Comment by ptomin** [comment]
Now it runs regression tests and compare outputs with ones in repository. If they differ they are marked as failed. So if output for tests is changed the author of change should push updates of regression tests to repository.

**Pull request merged**
