### PR TITLE
Create hotkey for comment editing

### PR DESCRIPTION
**Pull request by ptomin**
Use `Ctrl+T` (T - Text) as hotkey for comment editing. Do you agree, John?

### CODE REVIEW

**Comment by uxmal** [comment]
Well, `Ctrl+T` is already used to mark memory regions of memory with a **T**ype in the memory control. I was actually going to suggest the simple command `;` (semicolon). What do you think?

**Comment by ptomin** [comment]
`;` without `Ctrl`?

**Comment by uxmal** [comment]
Yes, a simple semicolon. This is not a general text editor, so commands without a `Ctrl` prefix is fine.

**Comment by ptomin** [comment]
`OemSemicolon` works on my machine

**Comment by uxmal** [comment]
OK, let's go with that for now. It's possible that German or French users may complain. I'm not going to worry until we get bug reports for it. Having the capability of changing the key bindings will certainly help.

**Pull request merged**
