### PR TITLE
Do not lose label during edge virtualization 

### PR DESCRIPTION
**Pull request by ptomin**
Do not lose label during edge virtualization if destination region has not statements

### CODE REVIEW

**Comment by uxmal** [comment]
@ptomin: at first glance (I haven't had the time to look closely at the PR yet) it seems as if we're getting a lot of "dead" labels introduced here; it looks like a regression. Is this PR part of a series of improvements? It would be useful if you included a unit test that exhibits the issue you are trying to address.

**Comment by ptomin** [comment]
> it seems as if we're getting a lot of "dead" labels introduced here
Which of introduced labels are dead? I can not find any

**Comment by uxmal** [comment]
OK, I think I understand the change now. The labels were previously missing. Thanks for the PR!

**Comment by ptomin** [comment]
I have added unit test in 41b7797

**Comment by uxmal** [comment]
Thanks for the unit test, Pavel!

**Pull request merged**
